version: '3.9'

services:
  api:
    build: 
      context: ./backend
      dockerfile: ./docker/django/Dockerfile
    command: /start
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
     - hadronsom-react

  postgres-db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - hadronsom-react
  
  client:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    restart: on-failure
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - hadronsom-react

  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./backend/docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - hadronsom-react
networks:
  hadronsom-react:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: