# Generated by Django 5.0.6 on 2024-10-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_package_packageproduct_delete_packege"),
        ("products", "0012_categories_img_categories_img_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="products",
            field=models.ManyToManyField(
                through="packages.PackageProduct",
                to="products.products",
                verbose_name="Produtos do Pacote",
            ),
        ),
    ]
