# Generated by Django 5.0.6 on 2024-09-15 19:45

import django.db.models.deletion
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                ("number", models.CharField(max_length=10, verbose_name="Nº")),
                (
                    "neighborhood",
                    models.CharField(max_length=100, verbose_name="Bairro"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Cidade")),
                ("state", models.CharField(max_length=2, verbose_name="Estado")),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nome da rede social"),
                ),
                ("link", models.URLField(verbose_name="Link da rede social")),
                (
                    "icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="icons.iconfa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da empresa"),
                ),
                (
                    "logo",
                    imagefield.fields.ImageField(
                        blank=True,
                        height_field="logo_height",
                        upload_to="logo/",
                        verbose_name="imagem",
                        width_field="logo_width",
                    ),
                ),
                ("cnpj", models.CharField(max_length=18, verbose_name="CNPJ")),
                ("cep", models.CharField(max_length=9, verbose_name="CEP")),
                ("phone", models.CharField(max_length=15, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "opening_hours",
                    models.CharField(
                        max_length=255, verbose_name="Horário de funcionamento"
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(max_length=15, verbose_name="Número do Whatsapp"),
                ),
                (
                    "meta_title",
                    models.CharField(max_length=255, verbose_name="Título do site"),
                ),
                (
                    "meta_description",
                    models.TextField(verbose_name="Descrição do site"),
                ),
                ("meta_keywords", models.TextField(verbose_name="Palavras-chave")),
                (
                    "logo_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "logo_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "logo_ppoi",
                    imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
                ),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="company_profile.address",
                    ),
                ),
                (
                    "address_icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="address_icon",
                        to="icons.iconfa",
                    ),
                ),
                (
                    "email_icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_icon",
                        to="icons.iconfa",
                    ),
                ),
                (
                    "opening_hours_icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opening_hours_icon",
                        to="icons.iconfa",
                    ),
                ),
                (
                    "phone_icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phone_icon",
                        to="icons.iconfa",
                    ),
                ),
                (
                    "social_media",
                    models.ManyToManyField(
                        to="company_profile.socialmedia", verbose_name="Redes sociais"
                    ),
                ),
            ],
        ),
    ]
