# Generated by Django 5.0.6 on 2024-09-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="social_media",
        ),
        migrations.AddField(
            model_name="address",
            name="company_profile",
            field=models.ForeignKey(
                default=145,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="company_profile.companyprofile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="company_profile",
            field=models.ForeignKey(
                default=145,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_profiles",
                to="company_profile.companyprofile",
            ),
            preserve_default=False,
        ),
    ]
