# Generated by Django 5.0.6 on 2024-09-15 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0002_remove_companyprofile_social_media_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyprofile",
            options={
                "verbose_name": "Dados da Empresa",
                "verbose_name_plural": "Dados da Empresa",
            },
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="phone",
            field=models.CharField(
                help_text="Formato de telefone: +55 (DD) XXXX-XXXX",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de telefone inválido. Use: +55 (DD) XXXX-XXXX",
                        regex="^\\+55 \\(\\d{2}\\) \\d{4,5}-\\d{4})$",
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="whatsapp_number",
            field=models.CharField(
                help_text="Formato de telefone: +55 (DD) XXXX-XXXX",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de telefone inválido. Use: +55 (DD) XXXX-XXXX",
                        regex="^\\+55 \\(\\d{2}\\) \\d{4,5}-\\d{4})$",
                    )
                ],
                verbose_name="Número do Whatsapp",
            ),
        ),
    ]
