# Generated by Django 5.0.6 on 2024-09-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0004_alter_companyprofile_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="link",
            field=models.URLField(max_length=500, verbose_name="Link da rede social"),
        ),
    ]
