# Generated by Django 5.0.6 on 2024-09-16 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0008_alter_companyprofile_whatsapp_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="cep",
        ),
    ]
