# Generated by Django 5.0.6 on 2024-09-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_profile", "0009_remove_companyprofile_cep"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Token do Instagram",
                "verbose_name_plural": "Token do Instagram",
            },
        ),
    ]
