# Generated by Django 5.0.6 on 2024-09-09 07:57

import django.db.models.deletion
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("position", models.CharField(max_length=255, verbose_name="Cargo")),
                (
                    "img",
                    imagefield.fields.ImageField(
                        blank=True,
                        height_field="img_height",
                        upload_to="team/",
                        verbose_name="Imagem",
                        width_field="img_width",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "img_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "img_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "img_ppoi",
                    imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
                ),
            ],
            options={
                "verbose_name": "Time",
                "verbose_name_plural": "Time",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "img",
                    imagefield.fields.ImageField(
                        blank=True,
                        height_field="img_height",
                        upload_to="timeline/",
                        verbose_name="Imagem",
                        width_field="img_width",
                    ),
                ),
                ("year", models.DateField(verbose_name="Data")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "img_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "img_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "img_ppoi",
                    imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
                ),
            ],
            options={
                "verbose_name": "Linha do tempo",
                "verbose_name_plural": "Linhas do tempo",
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="icons.iconfa",
                        verbose_name="Icone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
                "ordering": ["title"],
            },
        ),
    ]
