# Generated by Django 5.0.6 on 2024-09-09 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_page", "0001_initial"),
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "color",
                    models.CharField(
                        default="#1877F2", max_length=7, verbose_name="Cor do icone"
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="icons.iconfa",
                        verbose_name="Icone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "social_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="about_page.socialnetwork",
                        verbose_name="Rede social",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="about_page.team",
                        verbose_name="Time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rede social do time",
                "verbose_name_plural": "Redes sociais do time",
                "ordering": ["team"],
            },
        ),
    ]
