# Generated by Django 5.0.6 on 2024-09-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_page", "0002_socialnetwork_teamsocialnetwork"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialnetwork",
            options={
                "ordering": ["name"],
                "verbose_name": "Rede social",
                "verbose_name_plural": "Redes sociais",
            },
        ),
    ]
