# Generated by Django 5.0.6 on 2024-08-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_text_1",
                    models.CharField(help_text="Primeiro texto", max_length=100),
                ),
                (
                    "hero_text_2",
                    models.CharField(help_text="Segundo texto", max_length=100),
                ),
                (
                    "hero_text_3",
                    models.CharField(help_text="Terceiro texto", max_length=100),
                ),
                (
                    "hero_bg_img",
                    models.ImageField(
                        help_text="Imagem de fundo para o Hero",
                        upload_to="backgrounds/",
                    ),
                ),
            ],
        ),
    ]
