# Generated by Django 5.0.6 on 2024-08-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_info",
                    models.CharField(
                        max_length=100, verbose_name="Título da Informação"
                    ),
                ),
                (
                    "description_info",
                    models.TextField(verbose_name="Descrição da Informação"),
                ),
            ],
            options={
                "verbose_name": "Sobre a empresa",
                "verbose_name_plural": "Sobre a empresa",
            },
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="A solução para o seu som é", max_length=255
                    ),
                ),
                ("hero_text_1", models.CharField(max_length=255)),
                ("hero_text_2", models.CharField(max_length=255)),
                ("hero_text_3", models.CharField(max_length=255)),
                ("hero_bg_img", models.ImageField(upload_to="hero_bg_img/")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "hero_description",
                    models.TextField(
                        default="Transforme qualquer espaço com as caixas de som Hádron.A combinação perfeita entre estilo e qualidade sonora que se adapta a todos os ambientes."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Digite o título",
                        max_length=100,
                        verbose_name="Título do Card",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Digite sua descrição", verbose_name="Descrição do Card"
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="icons.iconfa",
                    ),
                ),
                (
                    "about_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="home_page.aboutsection",
                    ),
                ),
            ],
        ),
    ]
