# Generated by Django 5.0.6 on 2024-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
