# Generated by Django 5.0.6 on 2024-08-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0001_initial"),
        ("icons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsServicesSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_info",
                    models.CharField(
                        default="Conheca nossos produtos",
                        max_length=100,
                        verbose_name="Título da Informação",
                    ),
                ),
                (
                    "description_info",
                    models.TextField(
                        default="Caixas de som, equipamentos, móveis para seu som e muito mais",
                        verbose_name="Descrição da Informação",
                    ),
                ),
                ("image1", models.ImageField(upload_to="products_services_section/")),
                ("alt_text1", models.CharField(blank=True, max_length=255, null=True)),
                ("image2", models.ImageField(upload_to="products_services_section/")),
                ("alt_text2", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProducstsServicesCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Ditite o título",
                        max_length=100,
                        verbose_name="Título do card",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Digite sua descrição", verbose_name="Descrição do Card"
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="icons.iconfa",
                    ),
                ),
                (
                    "products_services_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="home_page.productsservicessection",
                    ),
                ),
            ],
        ),
    ]
