# Generated by Django 5.0.6 on 2024-08-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0002_hero_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hero",
            name="is_active",
        ),
    ]
