# Generated by Django 5.0.6 on 2024-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0002_productsservicessection_producstsservicescard"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Pergunta")),
                ("answer", models.TextField(verbose_name="Resposta")),
            ],
            options={
                "verbose_name": "Perguntas frequentes",
                "verbose_name_plural": "Perguntas frequentes",
            },
        ),
    ]
