# Generated by Django 5.0.6 on 2024-09-03 12:35

import django.db.models.deletion
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0003_faqsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="home_page.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    imagefield.fields.ImageField(
                        blank=True,
                        height_field="avatar_height",
                        upload_to="avatars/",
                        verbose_name="Imagem",
                        width_field="avatar_width",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("testimonials", models.TextField()),
                (
                    "avatar_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "avatar_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "avatar_ppoi",
                    imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home_page.city"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home_page.state",
                    ),
                ),
            ],
        ),
    ]
