# Generated by Django 5.0.6 on 2024-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0003_remove_hero_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hero",
            name="hero_bg_img",
            field=models.ImageField(upload_to="hero_bg_img/"),
        ),
        migrations.AlterField(
            model_name="hero",
            name="hero_text_1",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="hero",
            name="hero_text_2",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="hero",
            name="hero_text_3",
            field=models.CharField(max_length=255),
        ),
    ]
