# Generated by Django 5.0.6 on 2024-09-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0004_state_city_testimonials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
