# Generated by Django 5.0.6 on 2024-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0004_hero_is_active_alter_hero_hero_bg_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hero",
            name="hero_description",
            field=models.TextField(
                default="Transforme qualquer espaço com as caixas de som Hádron.A combinação perfeita entre estilo e qualidade sonora que se adapta a todos os ambientes."
            ),
        ),
        migrations.AddField(
            model_name="hero",
            name="hero_title",
            field=models.CharField(
                default="A solução para o seu som é", max_length=255
            ),
        ),
    ]
