# Generated by Django 5.0.6 on 2024-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0005_hero_hero_description_hero_hero_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_info",
                    models.CharField(
                        max_length=100, verbose_name="Título da Informação"
                    ),
                ),
                (
                    "description_info",
                    models.TextField(verbose_name="Descrição da Informação"),
                ),
                (
                    "title_card",
                    models.CharField(max_length=100, verbose_name="Título do Card"),
                ),
                (
                    "description_card",
                    models.TextField(verbose_name="Descrição do Card"),
                ),
                (
                    "icon_card",
                    models.CharField(
                        choices=[
                            ("FaBoxOpen", "FaBoxOpen"),
                            ("FaTools", "FaTools"),
                            ("FaTruck", "FaTruck"),
                            ("FaWrench", "FaWrench"),
                        ],
                        max_length=50,
                        verbose_name="Ícone do Card",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção Sobre",
                "verbose_name_plural": "Seções Sobre",
            },
        ),
    ]
