# Generated by Django 5.0.6 on 2024-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0005_alter_state_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonials",
            name="cep",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Nome do local"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome do Cliente"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="state",
            field=models.CharField(max_length=2, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="testimonials",
            field=models.TextField(verbose_name="Mensagem"),
        ),
    ]
