# Generated by Django 5.0.6 on 2024-08-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0006_aboutsection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutsection",
            options={"verbose_name": "Sobre a empresa"},
        ),
    ]
