# Generated by Django 5.0.6 on 2024-09-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0006_testimonials_cep_alter_testimonials_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonials",
            options={
                "verbose_name": "Depoimentos",
                "verbose_name_plural": "Depoimentos",
            },
        ),
    ]
