# Generated by Django 5.0.6 on 2024-09-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0007_alter_testimonials_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
