# Generated by Django 5.0.6 on 2024-08-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0007_alter_aboutsection_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutsection",
            options={
                "verbose_name": "Sobre a empresa",
                "verbose_name_plural": "Sobre a empresa",
            },
        ),
    ]
