# Generated by Django 5.0.6 on 2024-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0008_alter_aboutsection_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsection",
            name="description_card",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="icon_card",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="title_card",
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="description_card_1",
            field=models.TextField(
                default="ditite seu texto", verbose_name="Descrição do Card 1"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="description_card_2",
            field=models.TextField(
                default="ditite seu texto", verbose_name="Descrição do Card 2"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="description_card_3",
            field=models.TextField(
                default="ditite seu texto", verbose_name="Descrição do Card 3"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="description_card_4",
            field=models.TextField(
                default="ditite seu texto", verbose_name="Descrição do Card 4"
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="icon_card_1",
            field=models.CharField(
                choices=[
                    ("FaBoxOpen", "FaBoxOpen"),
                    ("FaTools", "FaTools"),
                    ("FaTruck", "FaTruck"),
                    ("FaWrench", "FaWrench"),
                ],
                default="FaBoxOpen",
                max_length=50,
                verbose_name="Ícone do Card 1",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="icon_card_2",
            field=models.CharField(
                choices=[
                    ("FaBoxOpen", "FaBoxOpen"),
                    ("FaTools", "FaTools"),
                    ("FaTruck", "FaTruck"),
                    ("FaWrench", "FaWrench"),
                ],
                default="FaBoxOpen",
                max_length=50,
                verbose_name="Ícone do Card 2",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="icon_card_3",
            field=models.CharField(
                choices=[
                    ("FaBoxOpen", "FaBoxOpen"),
                    ("FaTools", "FaTools"),
                    ("FaTruck", "FaTruck"),
                    ("FaWrench", "FaWrench"),
                ],
                default="FaBoxOpen",
                max_length=50,
                verbose_name="Ícone do Card 3",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="icon_card_4",
            field=models.CharField(
                choices=[
                    ("FaBoxOpen", "FaBoxOpen"),
                    ("FaTools", "FaTools"),
                    ("FaTruck", "FaTruck"),
                    ("FaWrench", "FaWrench"),
                ],
                default="FaBoxOpen",
                max_length=50,
                verbose_name="Ícone do Card 4",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="title_card_1",
            field=models.CharField(
                default="digite o título",
                max_length=100,
                verbose_name="Título do Card 1",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="title_card_2",
            field=models.CharField(
                default="digite o título",
                max_length=100,
                verbose_name="Título do Card 2",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="title_card_3",
            field=models.CharField(
                default="digite o título",
                max_length=100,
                verbose_name="Título do Card 3",
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="title_card_4",
            field=models.CharField(
                default="digite o título",
                max_length=100,
                verbose_name="Título do Card 4",
            ),
        ),
    ]
