# Generated by Django 5.0.6 on 2024-08-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0009_remove_aboutsection_description_card_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsection",
            name="description_card_1",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="description_card_2",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="description_card_3",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="description_card_4",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="icon_card_1",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="icon_card_2",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="icon_card_3",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="icon_card_4",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="title_card_1",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="title_card_2",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="title_card_3",
        ),
        migrations.RemoveField(
            model_name="aboutsection",
            name="title_card_4",
        ),
        migrations.CreateModel(
            name="AboutCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Digite o título",
                        max_length=100,
                        verbose_name="Título do Card",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Digite sua descrição", verbose_name="Descrição do Card"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("FaBoxOpen", "FaBoxOpen"),
                            ("FaTools", "FaTools"),
                            ("FaTruck", "FaTruck"),
                            ("FaWrench", "FaWrench"),
                        ],
                        default="FaBoxOpen",
                        max_length=50,
                        verbose_name="Ícone do Card",
                    ),
                ),
                (
                    "about_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="home_page.aboutsection",
                    ),
                ),
            ],
        ),
    ]
