# Generated by Django 5.0.6 on 2024-08-29 07:54

import django.db.models.deletion
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "images",
                    imagefield.fields.ImageField(
                        blank=True,
                        height_field="images_height",
                        upload_to="products_images/",
                        verbose_name="Imagem",
                        width_field="images_width",
                    ),
                ),
                ("description", models.TextField()),
                ("detailed_description", models.TextField(blank=True)),
                ("specifications", models.JSONField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("on_sale", models.BooleanField(default=False)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "images_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "images_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "images_ppoi",
                    imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categories",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
