# Generated by Django 5.0.6 on 2024-08-29 08:36

import django.db.models.deletion
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="images",
        ),
        migrations.RemoveField(
            model_name="products",
            name="images_height",
        ),
        migrations.RemoveField(
            model_name="products",
            name="images_ppoi",
        ),
        migrations.RemoveField(
            model_name="products",
            name="images_width",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagefield.fields.ImageField(
                        blank=True,
                        height_field="image_height",
                        upload_to="product_images/",
                        verbose_name="Imagem",
                        width_field="image_width",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_width",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "image_ppoi",
                    imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
