# Generated by Django 5.0.6 on 2024-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productimage_options_alter_products_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.RemoveField(
            model_name="products",
            name="slug",
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
