# Generated by Django 5.0.6 on 2024-08-31 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_products_options_remove_products_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da Marca"),
                ),
                ("slug", models.SlugField(blank=True, verbose_name="URL Amigável")),
            ],
            options={
                "verbose_name_plural": "Marcas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("specification", models.TextField(verbose_name="Especificação")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Especificações",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Especificações do Produto",
                "ordering": ["title"],
            },
        ),
    ]
