# Generated by Django 5.0.6 on 2024-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_products_specifications_products_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome da Categoria"),
        ),
    ]
