# Generated by Django 5.0.6 on 2024-08-31 18:28

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_categories_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nome do Cor")),
                (
                    "hex_code",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        image_field=None,
                        max_length=7,
                        samples=None,
                        verbose_name="Código Hexadecimal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cores",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cores",
                "ordering": ["name"],
                "unique_together": {("product", "hex_code")},
            },
        ),
    ]
