# Generated by Django 5.0.6 on 2024-09-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_productimage_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="sold_separately",
            field=models.BooleanField(
                default=True, verbose_name="Vendido Separadamente?"
            ),
        ),
    ]
