# Generated by Django 5.0.6 on 2024-09-30 10:34

import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_products_sold_separately"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="img",
            field=imagefield.fields.ImageField(
                blank=True,
                height_field="img_height",
                upload_to="category_images/",
                verbose_name="Imagem da categoria sem o fundo",
                width_field="img_width",
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="img_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="categories",
            name="img_ppoi",
            field=imagefield.fields.PPOIField(default="0.5x0.5", max_length=20),
        ),
        migrations.AddField(
            model_name="categories",
            name="img_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
