# Generated by Django 5.0.6 on 2024-10-04 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_categories_img_categories_img_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Insira o desconto em porcentagem (0-100).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="% de Desconto",
            ),
        ),
    ]
